;;; leetcode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from leetcode.el

(autoload 'leetcode-toggle-debug "leetcode" "\
Toggle debug." t)
(autoload 'leetcode "leetcode" "\
A wrapper for `leetcode--async', because emacs-aio can not be autoloaded.
see: https://github.com/skeeto/emacs-aio/issues/3." t)
(autoload 'leetcode-daily "leetcode" nil t)
(register-definition-prefixes "leetcode" '("leetcode-"))

;;; End of scraped data

(provide 'leetcode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; leetcode-autoloads.el ends here
